name: Deploy Spring Boot Application to Minikube via Argo CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Step 2: Create .kube directory and reset the kubeconfig
      - name: Reset kubeconfig
        run: |
          mkdir -p $HOME/.kube
          echo "" > $HOME/.kube/config

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build Spring Boot Application
        run: mvn clean package -DskipTests

      - name: Login Docker Hub
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/my-app:latest .

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/my-app:latest

#      - name: Update values.yaml
#        run: |
#          cd myapp
#          sed -i 's|APP_VERSION:.*|APP_VERSION: '${{ github.sha }}'|' values.yaml
#          git config --global user.name 'npermana'
#          git config --global user.email 'npermana@gmail.com'
#          git add values.yaml
#          git commit -m "Update values.yaml"
#          git push
#      - name: Set up Kubeconfig for Minikube
#        run: |
#          echo "${{ secrets.KUBECONFIG }}" > $HOME/.kube/config
#
#      - name: Apply Kubernetes Manifests (Argo CD Sync)
#        run: |
#          kubectl apply -f k8s/deployment.yaml
#          kubectl apply -f k8s/service.yaml
